version: '3.8'
services:
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  my_app:
    platform: linux/amd64
    build: ./my_app
    command: ./entrypoint.sh
    volumes:
      - ./my_app:/my_app
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: ./my_app/.env
  react-app:
    build: ./react-app
    command: npm run dev
    volumes:
      - ./react-app:/react-app
    ports:
      - 1337:1337
    depends_on:
      - my_app
    env_file: ./react-app/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=1337
volumes:
  postgres: